site_name: W800BT Plus for Linux
repo_url: https://github.com/vrcunha/w800btplus-for-linux
repo_name: vrcunha/w800btplus-for-linux
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR

markdown_extensions:
  - attr_list