[tool.poetry]
name = "w800btplus-for-linux"
version = "0.1.0"
description = ""
authors = ["Victor Cunha <cunhavictorr@gmail.com>"]
readme = "README.md"
packages = [{include = "w800btplus_for_linux"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
